apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/clarity-staging-4afe8/sofe3980u/binarycalculator
          name: binarycalculator
          ports:
            - containerPort: 8080
